export const QUERY_KEYS = {
  USER_PROFILE: "user_profile",
  FEEDBACKS: "feedbacks",
  FEEDBACK_BY_ID: "feedback_by_id",
  FEEDBACK_STATISTICS: "feedback_statistics",
  PROMOTIONS: "promotions",
  PROMOTION_BY_ID: "promotion_by_id",
  PROMOTION_BY_CODE: "promotion_by_code",
  ACTIVE_PROMOTIONS: "active_promotions",
  PROMOTION_STATISTICS: "promotion_statistics",
  PRODUCTS: "products",
  PRODUCT_BY_ID: "product_by_id",
  PRODUCTS_BY_COLLECTION: "products_by_collection",
  PRODUCT_STATISTICS: "product_statistics",
  PRODUCT_CATEGORIES: "product_categories",
  PRODUCT_CATEGORY_BY_ID: "product_category_by_id",
  PRODUCT_CATEGORIES_BY_PRODUCT: "product_categories_by_product",
  PRODUCT_CATEGORY_STATISTICS: "product_category_statistics",
  PRODUCT_CUSTOMS: "product_customs",
  PRODUCT_CUSTOM_BY_ID: "product_custom_by_id",
  PRODUCT_CUSTOMS_BY_CATEGORY: "product_customs_by_category",
  PRODUCT_CUSTOM_STATISTICS: "product_custom_statistics",
  ROLES: "roles",
  ROLE_BY_ID: "role_by_id",
  PERMISSIONS: "permissions",
  PERMISSION_BY_ID: "permission_by_id",
  ROLE_PERMISSIONS: "role_permissions",
  // User management
  USERS: "users",
  USER_BY_ID: "user_by_id",
  USER_ROLES: "user_roles",
  USER_PERMISSIONS: "user_permissions",
  USER_PERMISSION_CHECK: "user_permission_check",
  USER_ROLE_CHECK: "user_role_check",
  USERS_BY_ROLE: "users_by_role",
  // Dashboard statistics
  USERS_STATISTICS: "users_statistics",
  DASHBOARD_STATISTICS: "dashboard_statistics",
  // Consultations
  CONSULTATIONS: "consultations",
  CONSULTATION_BY_ID: "consultation_by_id",
};
